---
name: "Update traefik version" 

sources:
 traefik:
   name: Get traefik version
   kind: githubrelease
   spec:
     owner: traefik
     repository: traefik
     token: '{{ requiredEnv .github.token }}'
     typefilter:
       release: true
       draft: false
       prerelease: false
     versionfilter:
       kind: semver

targets:
  makefile:
    name: "Bump to latest traefik version in Makefile"
    kind: file
    scmid: default
    disablesourceinput: true
    spec:
      file: Makefile
      matchpattern: '(?m)^TAG \:\= (.*)'
      replacepattern: 'TAG := {{ source "traefik" }}$$(BUILD_META)'

scms:
  default:
    kind: github
    spec:
      token: '{{ requiredEnv .github.token }}'
      username: '{{ .github.username }}'
      user: '{{ .github.username }}'
      email: '{{ .github.email }}'
      owner: '{{ .github.owner }}'
      repository: '{{ .github.repository }}'
      branch: '{{ .github.branch }}'
      
actions:
    default:
        title: 'Bump traefik version to {{ source "traefik" }}'
        kind: github/pullrequest
        spec:
            automerge: false
            labels:
                - chore
                - skip-changelog
                - status/auto-created 
        scmid: default
